import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { fontMono, fontSans, fontSerif } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontSans.variable,
          fontMono.variable,
          fontSerif.variable,
          "font-sans"
        )}
      >
        {children}
      </body>
    </html>
  );
}
